### ISSUE TITLE
update please

### ISSUE THREAD

**Issue by brokeyuan** [Loedje/server_chat_log_history#2]
incompatable with 1.21.4，My previous version worked well, but there were errors after update 1.21.4 fabric server. Please

**Comment by Loedje** [comment]
Thanks for letting me know! I'll try and fix it today.

**Comment by Loedje** [comment]
Resolved! You can download version 1.9 now. Let me know if you experience any further problems.

**Comment by brokeyuan** [comment]
thank!!!
